"""Add usage limits to User model

Revision ID: 0e74c6cc3b6c
Revises: 649e4e7ad254
Create Date: 2025-10-15 16:16:26.570858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e74c6cc3b6c'
down_revision = '649e4e7ad254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Dodaj kolumny jako nullable
    op.add_column('user', sa.Column('monthly_upload_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_reset_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('plan_name', sa.String(length=50), nullable=True))
    
    # Ustaw wartości domyślne dla istniejących rekordów
    op.execute("UPDATE \"user\" SET monthly_upload_count = 0 WHERE monthly_upload_count IS NULL")
    op.execute("UPDATE \"user\" SET last_reset_date = CURRENT_DATE WHERE last_reset_date IS NULL")
    op.execute("UPDATE \"user\" SET plan_name = 'Free' WHERE plan_name IS NULL")
    
    # Zmień na NOT NULL
    op.alter_column('user', 'monthly_upload_count', nullable=False)
    op.alter_column('user', 'last_reset_date', nullable=False)
    op.alter_column('user', 'plan_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'plan_name')
    op.drop_column('user', 'last_reset_date')
    op.drop_column('user', 'monthly_upload_count')
    # ### end Alembic commands ###
