"""Add is_active to Plan model

Revision ID: 649e4e7ad254
Revises: 8d88d777e678
Create Date: 2025-09-22 09:51:37.688885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649e4e7ad254'
down_revision = '8d88d777e678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # UWAGA: Oryginalny, automatycznie wygenerowany plik migracji był wadliwy.
    # Został on poprawiony, aby dodawał tylko kolumnę 'is_active' do tabeli 'plan', zgodnie z przeznaczeniem.
    # Wszystkie nieprawidłowe operacje drop_column() zostały usunięte.
    
    with op.batch_alter_table('plan', schema=None) as batch_op:
        # Dodajemy kolumnę 'is_active' jako nienullowalną.
        # Użycie `server_default=sa.true()` jest kluczowe, aby zapewnić,
        # że istniejące wiersze w tabeli otrzymają wartość domyślną `TRUE`,
        # co zapobiega błędowi przy migracji na niepustej tabeli.
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Ta funkcja poprawnie cofa dodanie kolumny 'is_active'.
    # Użycie `batch_alter_table` jest dobrą praktyką zapewniającą kompatybilność m.in. z SQLite.
    
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
