"""Add subscription_status to User

Revision ID: 6699cc11477b
Revises: 92787fa82da8
Create Date: 2025-09-22 09:19:30.291192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6699cc11477b'
down_revision = '92787fa82da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_status')
    # ### end Alembic commands ###
