"""Add subscription_status to User model

Revision ID: 8d88d777e678
Revises: 6699cc11477b
Create Date: 2025-09-22 09:20:42.946231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d88d777e678'
down_revision = '6699cc11477b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
