"""Add admin role and Plan model

Revision ID: 92787fa82da8
Revises: e6ea2c7f82b6
Create Date: 2025-09-21 10:00:49.657884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92787fa82da8'
down_revision = 'e6ea2c7f82b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=120), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stripe_price_id'),
    sa.UniqueConstraint('stripe_product_id')
    )
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_table('plan')
    # ### end Alembic commands ###
