"""Add stripe_customer_id to User model

Revision ID: e6ea2c7f82b6
Revises: a1b2c3d4e5f6
Create Date: 2025-09-21 09:53:00.176982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ea2c7f82b6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
